"""erf

Revision ID: a106c2fc11af
Revises: ae8113ac5306
Create Date: 2023-07-12 23:33:35.519973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a106c2fc11af'
down_revision = 'ae8113ac5306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier', schema=None) as batch_op:
        batch_op.alter_column('description_du_defaut',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier', schema=None) as batch_op:
        batch_op.alter_column('description_du_defaut',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
