"""version2

Revision ID: b79c4a9ed60c
Revises: 58724a691750
Create Date: 2023-07-07 11:49:07.217126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79c4a9ed60c'
down_revision = '58724a691750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier', schema=None) as batch_op:
        batch_op.drop_column('confirm')

    # ### end Alembic commands ###
