"""version2

Revision ID: bc98f74a1808
Revises: 0295525d8560
Create Date: 2023-07-03 16:52:38.273366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc98f74a1808'
down_revision = '0295525d8560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corbeille', schema=None) as batch_op:
        batch_op.drop_index('login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corbeille', schema=None) as batch_op:
        batch_op.create_index('login', ['login'], unique=False)

    # ### end Alembic commands ###
