"""version2

Revision ID: c82f838c40c7
Revises: 0abf9abf7b6a
Create Date: 2023-07-06 11:18:14.689983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82f838c40c7'
down_revision = '0abf9abf7b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
